### ISSUE TITLE
请问能否增加启动器的编译

### ISSUE THREAD

**Issue by FallenNoober** [qe201020335/SPT-AKI_CI#1]
即SPT-AKI
/
Launcher的部分，不知能否添加这一部分的每日编译，补全整个构建的必须项
https://dev.sp-tarkov.com/SPT-AKI/Launcher

**Comment by qe201020335** [comment]
即使包含了启动器的编译，也不是完整的分发，因为缺少Assembly-CSharp.dll。

这个文件包含bsg的代码所以我不能提供。Aki团队有工具来做反混淆差异补丁所以他们的分发里也不包含这个文件。我可以用他们的工具来反混淆并生成差异文件，但我不清楚具体的反混淆和重命名参数，所以我也不能确定我自己反混淆的dll是否可用。

**Comment by qe201020335** [comment]
Just realized that they provide the diff patch file in the launcher repo. 

Will add support to build the entire aki release. It needs to also include BepInEx and other files that the aki team bundled in their release.

**Comment by qe201020335** [comment]
Done.
