### ISSUE TITLE
请问下怎么搞才能挂mod啊？

### ISSUE THREAD

**Issue by yhl452493373** [qe201020335/SPT-AKI_CI#2]
我fork你的，然后编译时加了-Release参数，编译出来的东西，启动后已经没有提示为BE版，不能挂mod了。但是我在plugin下加了mod后，启动游戏，提示我be版本不能加载非debug模式的客户端插件。

**Comment by qe201020335** [comment]
首先，debug和release都不会影响服务器mod加载，debug也不是BE版只是会显示BE的文字。debug就是debug，报错的时候信息会详细一些。

第二，你在plugins里加的mod是客户端mod，不能加载的原因也不是因为BE。客户端是可以加载mod的，但Aki在他们的Modules代码里死了检测，原理是在游戏启动之后检查所有加载的mod，如果发现有不在白名单中的mod，就强行报错。

想绕过客户端mod检测除了删除相关代码重新编译之外，就是通过另一个mod来跳过检测。我写了一个在这个repo：https://github.com/qe201020335/SPTClientMods/tree/master/YeetAntiMod

**Comment by yhl452493373** [comment]
好的，多谢

**Comment by yhl452493373** [comment]
> 我就寻思为什么你要在fork里把服务器编译变成Release的 🤦 ，你的理解有几个误区
> 
> 首先，debug和release都不会影响服务器mod加载。debug也不是BE版，只是会显示BE的文字。debug就是允许调试，报错的时候信息会详细一些。
> 
> 第二，你在plugins里加的mod是客户端mod，不能加载的原因也不是因为BE。客户端是可以加载mod的（除非他们魔改BepInEx），只不过Aki在他们的Modules代码里添加了检测（不论是不是BE），原理是在游戏启动之后检查所有已加载的mod，如果发现有不在白名单中的mod，就强行报错。Aki的客户端mod检测代码在这：https://dev.sp-tarkov.com/SPT-AKI/Modules/src/branch/3.8.0/project/Aki.Core/Patches/PreventClientModsPatch.cs
> 
> 想绕过客户端mod检测除了删除相关代码并重新编译Modules之外，就是通过另一个mod来跳过检测。我写了一个在这个repo：https://github.com/qe201020335/SPTClientMods/tree/master/YeetAntiMod 编译好的: [3.8.0 BE解除游戏端mod限制.zip](https://github.com/qe201020335/SPT-AKI_CI/files/14476549/3.8.0.BE.mod.zip)
> 
> 如果你决定要加mod，那么一定不要向Aki团队回报问题。有问题的话可以加我的Discord，搜qe201020335

感谢了，我一直以为release就不会检测mod了，我理解错误了。
